[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "templates"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
